import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google"
import "../globals.css";
import SearchComponent from "@/components/SearchComponent";
import MainMenuComponents from "@/components/MainMenuComponents";
import { FaStore } from "react-icons/fa";
import { FcSalesPerformance } from "react-icons/fc";
import { IoPeopleSharp } from "react-icons/io5";
import { SiGoogleanalytics } from "react-icons/si";
import { TbReportAnalytics } from "react-icons/tb";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const poppins = Poppins({
  weight: "400"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gray-950 h-dvh w-full text-white ">
          <div className="flex ">
            <div className="w-[14vw] my-7 mx-5 break-words flext flex-col items-start">
              <div className="">
                <div className={`text-[27px] mb-8 font-bold ${poppins.className}`}>Dashboard</div>
                <SearchComponent />
                <MainMenuComponents menuName="Inventory" icon={<FaStore />} itemroute="/inventory" />
                <MainMenuComponents menuName="Customer" icon={<IoPeopleSharp />} itemroute="customers" />
                <MainMenuComponents menuName="Sales Analytics" icon={<FcSalesPerformance />} itemroute="sales_analytics" />
                <MainMenuComponents menuName="Social Media" icon={<SiGoogleanalytics />} itemroute="social_medias" />
                <MainMenuComponents menuName="Loyality Program" icon={<TbReportAnalytics />} itemroute="loyality_program" />
              </div>

            </div>

            <div className={`w-[83vw] h-[96vh] bg-gray-100 rounded-3xl mx-3 mt-3 mb-2 p-4 overflow-auto text-black ${poppins.className}`}>
              {children}
            </div>
          </div>
        </div>

      </body>
    </html>
  );
}
